name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: |
        pip install uv
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    - name: Lint with flake8
      run: |
        flake8 smarthep_singleparticlejes tests
    - name: Check formatting with black
      run: |
        black --check smarthep_singleparticlejes tests
    - name: Check imports with isort
      run: |
        isort --check smarthep_singleparticlejes tests
    - name: Type check with mypy
      run: |
        mypy smarthep_singleparticlejes
    - name: Test with pytest
      run: |
        pytest --cov=smarthep_singleparticlejes tests/

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install uv
      run: |
        pip install uv
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
        uv pip install sphinx sphinx_rtd_theme
    - name: Build documentation
      run: |
        cd docs && make html
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
